development:
  adapter: postgresql
  database: scoreboard_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: scoreboard_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: scoreboard_production
  pool: 5
  timeout: 5000
